#!/usr/bin/env sh

request="$(head -n1)"

logdate() {
  printf %s "$(date "+%H:%M:%S")" >&2
}

method="$(printf %s "$request" | awk '{ print $1 }')"
path="$(printf %s "$request" | awk '{ sub(/^\//, "", $2); print $2 }')"

logdate
printf " > %s\n" "$request" >&2

logdate
printf " < " >&2
get "$method" "$path" | tee1 /dev/stderr

# head -n1 <&3 >&2
