#!/usr/bin/env sh

request="$(head -n1)"

logtime() {
  printf %s "$(date "+%H:%M:%S")" >&2
}

tee1() {
  head -n1 | tee "$1"
  cat
}

method="$(printf %s "$request" | awk '{ print $1 }')"
path="$(printf %s "$request" | awk '{ sub(/^\//, "", $2); print $2 }')"

logtime
printf " > %s\n" "$request" >&2

logtime
printf " < " >&2
get "$method" "$path" | tee1 /dev/stderr
printf "\r\n"
