#!/usr/bin/env sh

fail() {
  >&2 echo "http-body: $1"
  exit 1
}

if [ -z ${1+x} ]; then
  fail "must specify file path"
else
  file="$1"
fi

http-header "Content-Length" "$(cat "$1" | wc -c | tr -d ' ')"
http-begin-body
cat "$1"
